import { type Orders, type Product, type User } from "@prisma/client";
import { type GetServerSidePropsContext } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../../components/Header";
import { HomePage } from "../../components/home";
import { getServerAuthSession } from "../server/common/get-server-auth-session";
import { getUsername } from "../server/common/get-username";
import { getSession } from "../utils/next-session-store";



const Home =  ({admin,product,user,cartQty,orders}:{admin:boolean,product: Product[] | null | undefined,user: User,cartQty:number | null,orders:Orders[] | null}) => {
  
    return (
      <>
        <Header admin={admin} user={user} qty={cartQty} order={orders}/>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <HomePage />
          <section className="px-32 py-20">
            <div className="grid grid-cols-3 gap-14">
              {  
                product && 
                  product?.map((item:Product)=>(
                    <div key={item.id} className="bg-red-300 w-full  flex flex-col-reverse border-black border-2 justify-end rounded-lg">
                      <div className="w-full min-h-fit px-4 py-6">
                        <h2 className="text-2xl font-medium mb-2 capitalize">{item.title.length > 100 ? item.title.slice(0,50) : item.title}</h2>
                        <p>{item.descripton}</p>
                      </div>
                      <div className="w-full h-80 relative rounded-md">
                        <Link href={`/products/${item.id}`}>
                          <Image 
                            src={item.image || ""} 
                            alt="product-image"
                            layout="fill"
                            objectFit="cover"
                            className="h-full w-full"
                          />
                        </Link>
                      </div>
                    </div>
                  ))
              }
            </div>
          </section>
        </main>
      </>
    ); 
};

export default Home;

export async function getServerSideProps(ctx:GetServerSidePropsContext){

  const sessionUser = await getServerAuthSession(ctx);
  const props = await getUsername(sessionUser);
  const user = props.props.user;
  const sessionCookie = await getSession(ctx.req,ctx.res);
  const sessionCart:string | null = sessionCookie.cart?.id;

  if(user){
    const cart = await prisma?.cart?.findFirst({
      where:{
        userId:user?.id,
      }
    })
    const orders = await prisma?.orders.findMany({
      where:{
        userId:user?.id
      }
    })
    console.log(orders?.length)
    return {
      props:{
        user:props.props.user,
        admin:props.props.admin,
        product:props.props.product,
        cartQty:cart?.qty ? cart?.qty : 0,
        orders:orders
      }
    }

  }
  else if(sessionCart){
    const cart = await prisma?.cart.findFirst({
      where:{
        id:sessionCart,
      },
      select:{
        qty:true,
      }
    })
    const orders = await prisma?.orders.findMany({
      where:{
        sessionId:sessionCookie.id
      }
    })
    return {
      props:{
        user:props.props.user,
        admin:props.props.admin,
        product:props.props.product,
        cartQty:cart?.qty ? cart.qty : 0,
        orders:orders
      }
    }
  }

  return {
    props:{
      user:props.props.user,
      admin:props.props.admin,
      product:props.props.product,
      order:null
    }
  }
}

